# Generated by Django 3.0.2 on 2020-04-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationModule', '0002_auto_20200315_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_username',
        ),
    ]
