# Generated by Django 3.0.2 on 2020-04-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationModule', '0003_remove_student_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_username',
        ),
    ]
