# Generated by Django 3.0.2 on 2020-04-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSubmissions', '0006_auto_20200425_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_c_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
